#%RAML 1.0
title: Test API
description: 'To test stuff'
version: 2.0.0
mediaType: application/json
protocols:
  - HTTP

uses:     
  myLib : reused-fragment.raml

/test:
  post:
    description: adds stuff
    queryParameters:
      access_token:
        description: Access Token
        type: string
        example: ACCESS_TOKEN
        required: true
    body:
      application/json:
        type: myLib.stuff
  /{testId}/{version}:
    get:
      description: uses dependency type
      headers:
        stringHeader:
      responses:
        '200':
          description: a dependency type
          body:
            application/json:
              type: myLib.moreStuff

