#%RAML 1.0
title: Illustrate query parameter variations

types:
  author:
    properties:
      name: string
      lastname: string
      addresses?: array

/testNull:
  get:
    queryParameters:
        nullableString:
            type: string | nil
            required: false
        nonNullableString:
            type: string
            required: false
        nullableInteger:
            type: integer | nil
            required: false
        nonNullableInteger:
            type: integer
            required: false
        nullableArray:
            type: string[] | nil
            required: false
        nonNullableArray:
            type: string[]
            required: false

/books:
  get:
    queryParameters:
      author:
        displayName: Author
        type: author
        description: An author's full name
        required: false
        examples:
          author1:
            name: John
            lastname: Doe
          author2:
            name: Mary
            lastname: Doe
            addresses: [ 1st Street 125 ]
      publicationYear:
        displayName: Pub Year
        type: number
        description: The year released for the first time in the US
        required: false
      rating:
        displayName: Rating
        type: number
        description: Average rating (1-5) submitted by users
        example: 3.14
        required: false
      isbn:
        displayName: ISBN
        type: string
        minLength: 10
        example: '0321736079'
      tags:
        displayName: Tags
        type: string[]
        example: ["Comedy","Female author"]
        default: ["General"]

  delete:
    description: Delete an item by Code.
    body:
      multipart/form-data:
        properties:
          isbn:
            displayName: ISBN
            type: string
            minLength: 10
            example: '0321736079'